# autogenerated by txs
#include:xkeyval
\CheckCommandx#S
\DeclareRobustCommandx#S
\csname#S
\expandafter#S
\newcommandx#S
\newenvironmentx#S
\noexpand#S
\noexpand{arg1}#S
\providecommandx#S
\renewcommandx#S
\renewenvironmentx#S
\xargs#S
